### ISSUE TITLE
Dropping tmux

### ISSUE THREAD

**Issue by rwxrob** [rwxrob/books#2]
I've been back and forth on just how much magic to put into the code-mage (cm) command. I don't want to rob the people learning and reading from doing the setup themselves. But at the same time we really don't have time to get completely into everything that is in .bashrc, .vimrc and the rest.

I also hit a snag when i discovered that tmux and w3m are not available for Git Bash (nor WSL for that matter). Initially, this meant that I was going to require the installation of podman and a container image and then use cm work to dump the user into the container. The setup and magic inside code-mage at that point was overwhelming and makes for a very bloated learning setup (albeit still not as bloated as most webified approaches).

As I was working on the boilerplate in the Greet (Hello World) spell I realized just how much extra work is required just to run a simple Go program this way, and for what, so an absolute beginner can get the benefit of using w3m and tmux?

Having just also started the other Terminal Velocity book it became obvious that learning command line searching, AI queries, and tmux are topics for that book, not the "learn to code" book. So I decided to drop these from the install completely meaning that the only thing cm init will do is add a .bashrc and a .vimrc

I'm also not going to cover Neovim at all at this point. It makes sense later in Terminal Velocity.

**Comment by ivanvgav** [comment]
Rob, would not be a good idea, only for pedagogical purposes use in this case WSL in windows?

Take it like a place where the cm command can run without problem. In one of my computers I have windows and I'm running wsl so I can use neovim and tmux for writing and pandoc usage.
Tmux run perfectly.

It's only a suggestion.

Later you can teach as a final chapter how to move to a Unix system.
